name: Deploy

on:
  push:
    branches:
      - master
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.5"
      - run: flutter pub get
      - run: flutter build web
      - name: Install Firebase Tools
        run: |
          npm install -g firebase-tools
        working-directory: ./
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only hosting --token $FIREBASE_TOKEN
        working-directory: ./
